global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'consul'
    consul_sd_configs:
      - server: 127.0.0.1:8500
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: (.*)
        replacement: $1
        target_label: job
